Sprint1 amaituta
Nereee/E4_DB_T3 pull request #1
Opened 2024-04-22 06:10 UTC by Unaiiss

2024-04-22 07:10 UTC, Nereee requested changes

2024-04-22 07:10 UTC, Nereee commented on DB_Spotifi_Schema.sql
> +alter table Bezeroa
Hizkuntza bat ezin izango da ezabatu baldin eta bezero batek hizkuntza aukeratua baldin badu?

2024-04-22 07:10 UTC, Nereee commented on DB_Spotifi_Schema.sql
> +alter table Erreprodukzioak
Kontuan izan bezero bat ezabatuz gero erreprodukzioak ere ezabatuko dituzuela. Orduan, estatistikak nola kudeatuko dituzue?

2024-04-22 07:10 UTC, Nereee commented on DB_Spotifi_Schema.sql
> +alter table Estadistikak
Gogoratu estatistika taula oraindik amaitu barik dagoela, beraz edozein aldaketa taula honetan triggerrekin batera zuzenduko dugu

2024-04-22 07:10 UTC, Nereee commented on DB_Spotifi_Schema.sql
> +Iraupena int not null,
Iraipena ez al da errezago time mota ondoren datuak mahai gaineko aplikazioan erakusteko?
ID-ak char motan utziko dituzue? Ondo iruditzen zait, baina erabaki horiek hartu eta ez aldatu

2024-04-22 08:27 UTC, JonV-elorrieta commented on DB_Spotifi_Schema.sql
> +Iraupena int not null,
ID-ak char utziko ditugu bezeroa izan ezik, casu honetan auto-increment erabiltzea hobe dela uste dugulako, gero aplikazioan gure honerako.

2024-04-23 06:09 UTC, IkerGrani commented on DB_Spotifi_Schema.sql
> +alter table Estadistikak
Bai, badakit. Baina, oraindik ez dugu zehaztu zein datu gorde nahi dutugu. Markatu dut ez ahazteko

2024-04-23 06:20 UTC, closed without merging