Sprint2 amaituta
Nereee/E4_DB_T3 pull request #3
Opened 2024-04-29 08:06 UTC by Unaiiss

2024-04-30 07:05 UTC, Nereee requested changes
Hemen zuzenketak doaz, aipatzen ez dena primeran dago.

Eman buelta bat bista honi: TWPEntzumena (ez limitatu datu bakarrera).
Bista batzuen azalpenak falta dira. 

Rolekin aholkatzen dizuet matrize batera eramatea eta datuak gurutzatzea. Adibidez, Bezeroak ez du izan behar baimenik ESTATISTIKA taularen gainean. Matrizeak argituko dizue erlazio hori.

2024-04-30 09:05 UTC, Nereee requested changes

2024-04-30 09:05 UTC, Nereee commented on DB_Spotifi_Users.sql
> +GRANT SELECT ON DB_Sprotify.Estadistikak TO 'Bezeroa';
Hau ez duzue zuzendu!!!!

2024-04-30 09:50 UTC, IkerGrani commented on DB_Spotifi_Users.sql
> +GRANT SELECT ON DB_Sprotify.Estadistikak TO 'Bezeroa';
Bezeroa Estadistikari select ahal duela ezaten duzu?

2024-05-02 05:59 UTC, Nereee approved these changes

2024-05-02 05:59 UTC, merged